---
- name: Install apt-transport-https
  apt:
    name: apt-transport-https

- name: Import apt key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key

- name: Add repository
  apt_repository:
    repo: deb https://nginx.org/packages/mainline/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} nginx

- name: Install nginx package
  apt:
    name: "nginx{% if nginx_install_full_package %}-full{% endif %}"

- name: Set nginx config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    validate: /usr/sbin/nginx -t -c %s
  register: nginx_reload

- name: Place template PAM nginx file
  template:
    src: templates/pam_service_file.j2
    dest: "/etc/pam.d/{{ nginx_pam_service_name | mandatory }}"
  when: nginx_pam_rules is defined

- name: Enable and start nginx
  systemd:
    name: nginx.service
    state: reloaded
    enabled: True
  when: ansible_service_mgr == "systemd" and nginx_reload.changed

- name: Allow www-data to access shadow for PAM
  user:
    append: True
    groups: shadow
    name: www-data
  when: nginx_allow_shadow

# stupid shell workaround needed since ansible still lacks an option to remove users from groups
# see also: https://github.com/ansible/ansible/issues/11024
- name: Forbid www-data shadow group access
  shell: deluser www-data shadow
  register: nginx_allow_shadow_remove
  when: not nginx_allow_shadow
  changed_when: nginx_allow_shadow_remove.rc != 6
  failed_when: nginx_allow_shadow_remove.rc != 6 and nginx_allow_shadow_remove.rc != 0
